# Generated by Django 4.2.7 on 2024-02-08 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jobapplications_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplications',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.job'),
        ),
    ]
